<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Starcraft 2 - How Performance Metrics Relate to League Placement</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="FinalProj_files/libs/clipboard/clipboard.min.js"></script>
<script src="FinalProj_files/libs/quarto-html/quarto.js"></script>
<script src="FinalProj_files/libs/quarto-html/popper.min.js"></script>
<script src="FinalProj_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FinalProj_files/libs/quarto-html/anchor.min.js"></script>
<link href="FinalProj_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FinalProj_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FinalProj_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FinalProj_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FinalProj_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Starcraft 2 - How Performance Metrics Relate to League Placement</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.2.0 ──
✔ broom        1.0.6     ✔ rsample      1.2.1
✔ dials        1.3.0     ✔ tune         1.2.1
✔ infer        1.0.7     ✔ workflows    1.1.4
✔ modeldata    1.4.0     ✔ workflowsets 1.1.0
✔ parsnip      1.2.1     ✔ yardstick    1.3.1
✔ recipes      1.1.0     
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use suppressPackageStartupMessages() to eliminate package startup messages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'kableExtra' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart.plot' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: rpart

Attaching package: 'rpart'

The following object is masked from 'package:dials':

    prune</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vip' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'vip'

The following object is masked from 'package:utils':

    vi</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'xgboost' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'xgboost'

The following object is masked from 'package:dplyr':

    slice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(themis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'themis' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rawData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"starcraft_player_data.csv"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">kable_styling_bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>unregister <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  env <span class="ot">&lt;-</span> foreach<span class="sc">:::</span>.foreachGlobals</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>(<span class="at">name=</span>env), <span class="at">pos=</span>env)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="statement-of-purpose" class="level3">
<h3 class="anchored" data-anchor-id="statement-of-purpose">Statement of Purpose</h3>
<p>This report intends to analyze what factors contribute to or are predictive of high level Starcraft 2 play. In general The report will attempt to predict the “LeagueIndex” using statistics from a game replay. The statistics that are highly predictive of higher “LeagueIndex” are likely statistics that are worth training and improving as skills that improve your rank.</p>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<p>To start, the LeagueIndex column is our response variable. This value ranges from 1-8 and we will be attempting to use classification modeling to identify the most valuable predictors. The 1-8 value represents “Bronze, Silver, Gold, Platinum, Diamond, Master, GrandMaster, and Professional leagues.”</p>
<section id="class-imbalance-check" class="level4">
<h4 class="anchored" data-anchor-id="class-imbalance-check">Class Imbalance Check</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(rawData<span class="sc">$</span>LeagueIndex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6   7   8 
167 347 553 811 806 621  35  55 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>numGrandMaster <span class="ot">&lt;-</span> rawData <span class="sc">%&gt;%</span> <span class="fu">count</span>(LeagueIndex <span class="sc">==</span> <span class="dv">7</span>) </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>numGrandMaster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  LeagueIndex == 7    n
1            FALSE 3360
2             TRUE   35</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="dv">35</span><span class="sc">/</span><span class="dv">3395</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01030928</code></pre>
</div>
</div>
<p>It is rarest to be of LeagueIndex 7. Only 35 observations are GrandMasters (rank 7). This equates to 35/3395=0.01030928, so ~1% of the observations. This should be fair grounds for stratifying the dataset during the data splitting.</p>
</section>
<section id="converting-predictors-from-character-to-numeric" class="level4">
<h4 class="anchored" data-anchor-id="converting-predictors-from-character-to-numeric">Converting Predictors from Character to Numeric</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rawData <span class="ot">&lt;-</span> rawData <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="fu">as.numeric</span>(Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `Age = as.numeric(Age)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>rawData <span class="ot">&lt;-</span> rawData <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HoursPerWeek =</span> <span class="fu">as.numeric</span>(HoursPerWeek))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `HoursPerWeek = as.numeric(HoursPerWeek)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rawData <span class="ot">&lt;-</span> rawData <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TotalHours =</span> <span class="fu">as.numeric</span>(TotalHours))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `TotalHours = as.numeric(TotalHours)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
</div>
</section>
<section id="convert-leagueindex-response-to-categorical" class="level4">
<h4 class="anchored" data-anchor-id="convert-leagueindex-response-to-categorical">Convert LeagueIndex Response to Categorical</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>rawData <span class="ot">&lt;-</span> rawData <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">LeagueIndex =</span> <span class="fu">as.factor</span>(LeagueIndex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-split-and-cv-folds" class="level4">
<h4 class="anchored" data-anchor-id="data-split-and-cv-folds">Data Split and CV Folds</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">22</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dataSplits <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(rawData, <span class="at">prop =</span> <span class="fl">0.80</span>, <span class="at">strata =</span> LeagueIndex)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">training</span>(dataSplits)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">testing</span>(dataSplits)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># cross-validation folds </span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">22</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>trainFolds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train, <span class="at">v =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The dataset has been split into train and test by an 80/20 split. It is stratified using our response LeagueIndex so that both train and test have a proportional amount of each LeagueIndex rank. The train set is then split into 10 training folds to be used for cross validation later.</p>
</section>
<section id="first-look" class="level4">
<h4 class="anchored" data-anchor-id="first-look">First Look</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   GameID LeagueIndex Age HoursPerWeek TotalHours      APM SelectByHotkeys
1      60           2  27            6         70  44.4570    0.0009783903
2      61           1  21            8        240  46.9962    0.0008201141
3     181           2  25           10        200  75.9642    0.0006096651
4     187           2  25            8        100  79.1280    0.0005007704
5     220           2  27            8        280  55.0470    0.0006428090
6     234           2  16           24         50 109.0380    0.0043008666
7     263           2  22           16        450 114.9420    0.0017443669
8     288           2  32           10        400  53.8788    0.0013120511
9     333           2  16           28        300  76.8504    0.0007144174
10    398           7  24           16       1250 216.6852    0.0119572592
   AssignToHotkeys UniqueHotkeys MinimapAttacks MinimapRightClicks NumberOfPACs
1     2.552323e-04             2   0.000000e+00       0.000000e+00  0.002424707
2     1.685166e-04             6   0.000000e+00       4.493776e-05  0.001988496
3     1.368636e-04             4   1.244214e-04       3.234957e-04  0.002090280
4     8.988187e-05             4   1.926040e-05       1.720596e-03  0.002754237
5     1.264542e-04             0   7.376496e-05       9.484067e-05  0.002529085
6     1.778554e-04             6   0.000000e+00       0.000000e+00  0.003395421
7     2.999867e-04             2   2.222123e-05       8.888494e-05  0.002577663
8     6.905532e-05             4   0.000000e+00       9.865046e-05  0.001588272
9     3.572087e-04             1   0.000000e+00       1.037058e-04  0.001947364
10    3.957485e-04             6   5.276647e-04       8.386100e-04  0.005691241
   GapBetweenPACs ActionLatency ActionsInPAC TotalMapExplored WorkersMade
1         76.4405       98.7719       3.0965               16  0.00037221
2         94.0227       90.5311       4.1017               15  0.00057296
3         45.1018       78.3095       6.5417               15  0.00093316
4         50.5327       67.1422       5.3450               28  0.00043657
5         62.8452       83.8667       3.9333               22  0.00052689
6         28.5550       63.1429       4.8571               13  0.00101860
7         31.2208       61.5517       8.1379               22  0.00138880
8         21.3250      105.3416       5.6770               14  0.00047352
9         42.5714       82.5089       7.2249               18  0.00038025
10        21.6119       32.6225       5.0083               33  0.00068785
   UniqueUnitsMade ComplexUnitsMade ComplexAbilitiesUsed
1                6     0.000000e+00           0.0000e+00
2                5     0.000000e+00           0.0000e+00
3                6     0.000000e+00           0.0000e+00
4                6     0.000000e+00           6.4201e-06
5                6     0.000000e+00           1.7914e-04
6                6     0.000000e+00           8.0843e-05
7                7     1.555486e-04           9.7773e-04
8                7     0.000000e+00           0.0000e+00
9                3     0.000000e+00           0.0000e+00
10               8     3.769034e-05           0.0000e+00</code></pre>
</div>
</div>
<p>Immediately here, it must be noted that the SelectByHotkeys, AssignToHotkeys, MinimapAttacks, MinimapRightClicks, NumberOfPACs, GapBetweenPACs, WorkersMade, ComplexUnitsMade, and ComplexAbilitiesUsed are all columns generally composed of decimals less than 0.001. Some of those columns are generally less than 0.0001. This is because these columns are statistics measured <em>by timestep</em>. This means that these statistics take the game length into account, which is good in terms of predictive value. In longer games, a player should have more workers made, so the WorkersMade statistic is workers made per timestep rather than just workers made during a game. The thing to consider here is if the small numeric values will cause any problems or be underrepresented in the modeling process. Distance based modeling techniques like Support Vector Machines and K Nearest Neighbors certainly need scaled data, but these columns are not small enough that they would cause issues outside of that.</p>
<p>All the data is numeric and complete, so neither imputation nor dummy variables are necessary.</p>
</section>
<section id="plotting-predictors-against-response" class="level4">
<h4 class="anchored" data-anchor-id="plotting-predictors-against-response">Plotting Predictors Against Response</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>graphData <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">LeagueIndex =</span> <span class="fu">as.factor</span>(LeagueIndex)) <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TotalHours =</span> <span class="fu">ifelse</span>(TotalHours <span class="sc">&gt;</span> <span class="dv">10000</span>, <span class="cn">NA</span>, TotalHours))</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>potential_numeric_predictors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Age"</span>,<span class="st">"HoursPerWeek"</span>,<span class="st">"TotalHours"</span>,<span class="st">"APM"</span>,<span class="st">"SelectByHotkeys"</span>,<span class="st">"AssignToHotkeys"</span>,<span class="st">"UniqueHotkeys"</span>,<span class="st">"MinimapAttacks"</span>, <span class="st">"MinimapRightClicks"</span>, <span class="st">"NumberOfPACs"</span>,<span class="st">"GapBetweenPACs"</span>, <span class="st">"ActionLatency"</span>, <span class="st">"ActionsInPAC"</span>, <span class="st">"TotalMapExplored"</span>, <span class="st">"WorkersMade"</span>, <span class="st">"UniqueUnitsMade"</span>, <span class="st">"ComplexUnitsMade"</span>, <span class="st">"ComplexAbilitiesUsed"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots for each numeric predictor...the purrr library made it easier</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>plot_list <span class="ot">&lt;-</span> <span class="fu">map</span>(potential_numeric_predictors, <span class="cf">function</span>(var) {</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(graphData, <span class="fu">aes</span>(<span class="at">x =</span> LeagueIndex, <span class="at">y =</span> .data[[var]])) <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">outlier.color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Boxplot of"</span>, var, <span class="st">"by League Index"</span>), <span class="at">x =</span> <span class="st">"League Index"</span>, <span class="at">y =</span> var) <span class="sc">+</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The purpose of this section is to look at broad relationships between the predictors and the response. So we are simply looking at broad positive or negative relationships. Intuition would tell us that ActionLatency is bad for performance, but this step is double checking things like that.</p>
<p>Extreme outliers existed in TotalHours that were removed for the purpose of graphing. Some entries are certainly troll entries as one claims to have played for 114 years. Most of the entries are automatically gathered data, but the TotalHours must have been done by survey.</p>
</section>
<section id="positive-correlation" class="level4">
<h4 class="anchored" data-anchor-id="positive-correlation">Positive Correlation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">5</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">6</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">7</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-8-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-8-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are 8 potential predictors with clear positive correlation with LeagueIndex. Over half of these predictors, namely APM, SelectByHotKeys, AssignToHotkeys, UniqueHotkeys and NumberOfPACs, have strong, clear and consistent positive linear correlation to LeagueIndex. So these are skills that are consistently correlated with higher level play.</p>
<p>In context, better players have better APM (actions per minute). Better players also use more selection hotkeys. Lastly, better players have more PACs.</p>
<p>A higher APM means you are making more actions. This relates to the speed and efficiency of your play.</p>
<p>The three hotkey predictors are all related to using shortcuts to accomplish tasks. Instead of moving the camera and clicking to select things, better players use a single keyboard key to accomplish the same task. This is also indicative of the speed and efficiency you perform at. It also allows you to be making actions across more of the map than normal. You can only be looking at one area of the map at once, but hotkeys allow you to control things that are not on your screen.</p>
<p>A PAC is a “perception action cycle” that is basically a movement of the camera followed by some number of actions. More PACs means you are doing more things in different places on the map. Broadly it means that you are doing more things in different places at once. You are able to split your attention across the map better if you have more PACs.</p>
<p>Now, any player can simply improve all these stats by panning around the screen and spamming keyboard hotkeys like a madman, but that won’t help them climb the ranks. These are, however, great metrics to track your performance and for looking for areas of improvement. A lacking of any of these statistics likely means a disadvantage. Additionally, these statistics are all very related to the speed or efficiency that a player plays at. This is independent of game knowledge or strategy which are other important factors, but if you want to get better, you need to be able to do things as quickly as your opponent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 49 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 52 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">8</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">9</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The other predictors here, namely HoursPerWeek, TotalHours, MinimapAttacks and MinimapRightClicks, they have much smaller changes between lower LeagueIndex values but then jump up towards the higher LeagueIndex Values. So this second group of positive predictors might be able to define the difference between low level and high level play more broadly. Particularly, these predictors see significant increases in LeagueIndex 7 and 8 (the highest two leagues). So the best players use these skills the most.</p>
<p>Unfortunately the dataset seems to not have data for the TotalHours or HoursPerWeek of the players of rank 8 (the highest rank). This might have something to do with how the survey was dispersed.</p>
<p>So we cannot say whether the pattern would continue to rank 8, but there is a significant jump between ranks 5 and 6 in the HoursPerWeek predictor, and a there is a significant jump between ranks 6 and 7 in the TotalHours predictor. One way to interpret this is simply that it requires more and more hours to improve at the game as you get better. It looks like between 0 and ~700 TotalHours might have a very small linear increase between ranks 1-6, but then to get to rank 7 on average requires ~500 additional TotalHours. This is to say that, on average, putting more time in does not directly improve your skill necessarily. There are minor gains with TotalHours, so on average a player will improve the longer they play, but the additional HoursPerWeek seems unhelpful until ranks 6 and 7.</p>
<p>So, if you want to improve playing more should help a bit, but it does not need to be consistent. If you want to compete with the highest ranking players, you may have to dedicate a significant amount of time to play per week. Few people in ranks 6 or 7 play less than ~12 hours per week and most play ~20-30 hours a week.</p>
<p>Minimap attacks and right clicks allow the player to make actions that are off their screens. It means they can be acting in many places on the map at once while looking at only one part of it. It seems like between ranks 1-4, that this metric is not important. These players are likely overwhelmed enough that using these abilities does not help them. MinimapRighClicks increase only slightly until rank 8 where it jumps way up. MinimapAttacks increase only slightly until ranks 7 and 8 where it jumps way up. I would take this to describe these statistics as luxury statistics. Unless a player is gunning for the highest ranks, then these metrics are not terribly important for competing for ranks below 6. It is very possible for a player to climb lower ranks without using these mechanics very much at all.</p>
</section>
<section id="negative-correlation" class="level4">
<h4 class="anchored" data-anchor-id="negative-correlation">Negative Correlation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">11</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">12</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The GapBetweenPACs and ActionLatency predictors are strongly, consistently, and negatively correlated to LeagueIndex.</p>
<p>In context, this makes perfect sense. Action Latency is a measure of the mean delay between a screen movement and a new action. It is essentially the average length of PACs (time between moving the camera and then making your first action with the new location). Essentially, it is a delay between seeing new things and then making a decision on what needs to happen. Having a higher Action Latency means that you are taking longer between seeing something and deciding what to do (and usually doing something is better than not in Starcraft 2; things happen automatically, but usually player involvement can improve the outcome).</p>
<p>Action latency is essentially a measure of how quickly you react to things happening on your screen.</p>
<p>And the GapBetweenPACs is a measure of the mean delay between different PACs. This is essentially how long on average you keep the camera in one area. A higher value here means that you don’t move the camera as often (or you move the camera and don’t make actions often). A lower value here means you move the camera and make actions often.</p>
<p>The Gap Between PACs is essentially measuring how often you are moving around the map and making actions in response to new visual information. This measures how much new information you are capable of absorbing and how quickly you absorb it. It also measures how quickly you turn the new information into a retaliatory/responsive action.</p>
<p>Both of these metrics are therefore sensibly and statistically relevant to performance in Starcraft 2. If you want to improve your rank, these are metrics that should be noteworthy to you. You’ll want to minimize both of these metrics by being able to process information faster and make responsive actions faster.</p>
<p>It is perhaps interesting that both the number of PACs and the Gap Between PACs are entries in the dataset. I am unsure if these two metrics carry the same information. One is the total number per game, the other is the average delay between them. There is certainly overlap and the two graphs do look pretty similarly distributed (just oppositely correlated). To improve both of them, you do the same thing as well, you do more PACs.</p>
</section>
<section id="nolittle-correlation" class="level4">
<h4 class="anchored" data-anchor-id="nolittle-correlation">No/Little Correlation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 48 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">13</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">14</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">15</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">16</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">17</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_list[<span class="dv">18</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-11-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These last metrics, Age, ActionsInPAC, TotalMapExplored, WorkersMade, UniqueUnitesMade, ComplexUnitsMade, and ComplexAbilitiesUsed, they are all not obviously correlated to LeagueIndex. The age of rank 8 players is also missing like the TotalHours and HoursPerWeek. It is likely related to the survey method.</p>
<p>Starting with age, there does seem to be no real correlation between LeagueIndex and age. Few players in this dataset are over 25 years old and rank 6 and 7 players tend to be younger than 25 (which would explain the more hours per week).</p>
<p>The ActionsInPAC metric is a mean number of actions within a PAC. So, when the player moves the camera, this is a measure of the number of actions they make there before they move the camera again. This too seemed to stay pretty much the same across LeagueIndex. The number of actions you do after moving the camera is largely irrelevant then.</p>
<p>The TotalMapExplored metric is a measure of how much of the map is viewed per timestep. Essentially, this is a measure of how much raw visual information a player is getting on average during the game. There is also no strong correlation here with LeagueIndex. There is perhaps a small positive correlation because having more information is generally good, but it doesn’t really matter how much information you have if your aren’t responding to it quickly. If you get visual information and do not respond, it is like wasting that information and that time, which is why PACs and PAC delays are helpful metrics.</p>
<p>The WorkersMade metric is simply the number of workers made per timestep (so this scales with game length). A higher number means a player makes more workers. There is a small linear correlation between ranks 1-6 before it stagnates for rank 7 and then drops for rank 8. More workers is good generally, but it is sacrificing current resources for later resources which can be harmful. The priority is winning (ending) the game, so creating the minimal number of workers to win the game is optimal. Notably, the highest ranked players have a noticeably lower WorkersMade amount than ranks 5-7 meaning that these players are more optimal with their workers. They are less prone to creating more workers than they need.</p>
<p>The UniqueUnitsMade metric has no obvious correlation to LeagueIndex, but rank 8 players, on average, seem to know what they want more than rank 4-7 players. Ranks 1-3 players eventually learn that all the units have their position in the meta, then rank 5-7 players seem to make use of many of the total units often. Then finally, rank 8 players seem to be more picky about what they use, likely having the most extreme knowledge of the meta and which units are optimal.</p>
<p>Looking at the ComplexUnitsMade metric is the most interesting here because of the extreme loss between ranks 7 and 8. This is potentially only because there are fewer rank 8 players, but it may mean that the highest ranked players create less complex units, or that they simply do not lose the ones they create. Again, there is no clear correlation with LeagueIndex.</p>
<p>All of these metrics have some interesting potential findings, but none of them are greatly predictive of LeagueIndex. This implies that these metrics are not metrics that need to be focused on while improving your skills (though it does perhaps depend on your rank).</p>
</section>
</section>
<section id="modeling-section" class="level2">
<h2 class="anchored" data-anchor-id="modeling-section">Modeling Section</h2>
<p>Multiple models will be considered, particularly K Nearest Neighbors, Decision Tree, Random Forest, and XgBoost.</p>
<section id="knn-model" class="level3">
<h3 class="anchored" data-anchor-id="knn-model">KNN Model</h3>
<section id="knn-setup" class="level4">
<h4 class="anchored" data-anchor-id="knn-setup">KNN Setup</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>knnSpec <span class="ot">&lt;-</span> <span class="fu">nearest_neighbor</span>( <span class="at">neighbors =</span> <span class="fu">tune</span>()  ) <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"kknn"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>knnRec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(LeagueIndex <span class="sc">~</span> ., <span class="at">data =</span> train) <span class="sc">%&gt;%</span> </span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(GameID) <span class="sc">%&gt;%</span> </span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_median</span>(<span class="fu">all_numeric_predictors</span>()) </span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>knnWf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(knnSpec) <span class="sc">%&gt;%</span> </span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(knnRec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the KNN model, the “neighbors” hyperparameter is being tuned. All predictors are used to attempt to predict LeagueIndex. GameId is removed because it is not predictive, it is a label. The numeric predictors are normalized so that they have equally weighted votes. This solves the issue of the small values of some predictors. 20 initial hyperparameter combinations are being used and Bayesian Optimization explores the hyperparamter space further to look for even more optimal solutions.</p>
</section>
<section id="knn-tune" class="level4">
<h4 class="anchored" data-anchor-id="knn-tune">KNN Tune</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">makeCluster</span>(n_cores <span class="sc">-</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"PSOCK"</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">tic</span>()</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>knnTuneResults <span class="ot">&lt;-</span> knnWf <span class="sc">%&gt;%</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_bayes</span>(</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> trainFolds,</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(accuracy),</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">initial =</span> <span class="dv">20</span>,</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_bayes</span>(<span class="at">parallel_over =</span> <span class="st">"everything"</span>)</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in max(grid[[nm]], na.rm = TRUE): no non-missing arguments to max;
returning -Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>! No improvement for 10 iterations; returning current results.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>39.7 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unregister</span>()</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>knnTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 8
   neighbors .metric  .estimator  mean     n std_err .config               .iter
       &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                 &lt;int&gt;
 1         1 accuracy multiclass 0.314    10 0.0103  Preprocessor1_Model01     0
 2         2 accuracy multiclass 0.314    10 0.0103  Preprocessor1_Model02     0
 3         3 accuracy multiclass 0.314    10 0.0103  Preprocessor1_Model03     0
 4         4 accuracy multiclass 0.314    10 0.0103  Preprocessor1_Model04     0
 5         5 accuracy multiclass 0.313    10 0.0107  Preprocessor1_Model05     0
 6         6 accuracy multiclass 0.321    10 0.0101  Preprocessor1_Model06     0
 7         7 accuracy multiclass 0.328    10 0.0110  Preprocessor1_Model07     0
 8         9 accuracy multiclass 0.338    10 0.0104  Preprocessor1_Model08     0
 9        10 accuracy multiclass 0.337    10 0.0102  Preprocessor1_Model09     0
10        11 accuracy multiclass 0.338    10 0.00864 Preprocessor1_Model10     0
11        12 accuracy multiclass 0.340    10 0.00865 Preprocessor1_Model11     0
12        13 accuracy multiclass 0.341    10 0.00905 Preprocessor1_Model12     0
13        14 accuracy multiclass 0.343    10 0.00876 Preprocessor1_Model13     0
14        15 accuracy multiclass 0.344    10 0.00910 Preprocessor1_Model14     0
15         8 accuracy multiclass 0.333    10 0.0100  Iter1                     1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#33.32 sec elapsed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First off, the mean accuracy of all the iterations is around 32% which is not absolutely terrible because there are 8 response categories. It also makes sense that performance metrics are not the ultimate decider of ranked performance. A 30% predictor of rank makes intuitive sense for these metrics because we have no metrics for strategy or game knowledge at all. Any player could pretty easily force their metrics to look very good, but if they aren’t using these skills to do anything productive, they will never win. It would be like being the fastest runner on the football field but never running in the right direction and not knowing the rules of the game.</p>
<p>The best KNN model had an accuracy of ~35.3% using 15 voting neighbors.</p>
</section>
<section id="knn-fit" class="level4">
<h4 class="anchored" data-anchor-id="knn-fit">KNN Fit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>knnBestParams <span class="ot">&lt;-</span> knnTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"accuracy"</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>knnBestWf <span class="ot">&lt;-</span> knnWf <span class="sc">%&gt;%</span></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(knnBestParams)</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>knnBestFit <span class="ot">&lt;-</span> knnBestWf <span class="sc">%&gt;%</span></span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'kknn' was built under R version 4.4.2</code></pre>
</div>
</div>
<p>The fit was successful and will be used with test data at the end of the report.</p>
</section>
</section>
<section id="decision-tree-model" class="level3">
<h3 class="anchored" data-anchor-id="decision-tree-model">Decision Tree Model</h3>
<section id="decision-tree-setup" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree-setup">Decision Tree Setup</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>dtSpec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">tree_depth=</span><span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>dtRec <span class="ot">&lt;-</span>  <span class="fu">recipe</span>(LeagueIndex <span class="sc">~</span> ., <span class="at">data =</span> train) <span class="sc">%&gt;%</span> </span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(GameID)</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>dtWf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(dtSpec) <span class="sc">%&gt;%</span> </span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(dtRec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the Decision Tree model, the “tree_depth” and “min_n” hyperparameters are being tuned. All predictors are used to attempt to predict LeagueIndex. GameId is removed because it is not predictive, it is a label. 20 initial hyperparameter combinations are being used and Bayesian Optimization explores the hyperparamter space further to look for even more optimal solutions.</p>
</section>
<section id="decision-tree-tune" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree-tune">Decision Tree Tune</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">makeCluster</span>(n_cores <span class="sc">-</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"PSOCK"</span>)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">tic</span>()</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>dtTuneResults <span class="ot">&lt;-</span> dtWf <span class="sc">%&gt;%</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_bayes</span>(</span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> trainFolds,</span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(accuracy),</span>
<span id="cb105-11"><a href="#cb105-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">initial =</span> <span class="dv">20</span>,</span>
<span id="cb105-12"><a href="#cb105-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_bayes</span>(<span class="at">parallel_over =</span> <span class="st">"everything"</span>)</span>
<span id="cb105-13"><a href="#cb105-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! No improvement for 10 iterations; returning current results.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>40.7 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unregister</span>()</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>dtTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 9
   tree_depth min_n .metric  .estimator  mean     n std_err .config        .iter
        &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          &lt;int&gt;
 1          9    29 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 2          4    36 accuracy multiclass 0.346    10 0.00944 Preprocessor1…     0
 3          4    17 accuracy multiclass 0.346    10 0.00944 Preprocessor1…     0
 4         10    18 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 5          5    31 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 6          6    34 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 7          7    11 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 8          7     3 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
 9         14     7 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
10          5    20 accuracy multiclass 0.344    10 0.00965 Preprocessor1…     0
# ℹ 20 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#40.72 sec elapsed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The accuracy of all the decision trees are largely around ~35%. This accuracy is very similar to the result of the KNN model which is perhaps worrying especially because I see very similar accuracy results in many of these decision trees. This is perhaps worrying because it is possible that the models are selecting a single or few categories exclusively because the categories are skewed. The best performing decision tree will be fit and plotted to check on this.</p>
</section>
<section id="decision-tree-fit" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree-fit">Decision Tree Fit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>dtBestParams <span class="ot">&lt;-</span> dtTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"accuracy"</span>)</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>dtBestWf <span class="ot">&lt;-</span> dtWf <span class="sc">%&gt;%</span></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(dtBestParams)</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>dtBestFit <span class="ot">&lt;-</span> dtBestWf <span class="sc">%&gt;%</span></span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The fit was successful and will be used with test data at the end of the report.</p>
</section>
<section id="plotting-best-decision-tree" class="level4">
<h4 class="anchored" data-anchor-id="plotting-best-decision-tree">Plotting Best Decision Tree</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(dtBestFit <span class="sc">%&gt;%</span> <span class="fu">extract_fit_engine</span>() )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Cannot retrieve the data used to build the model (so cannot determine roundint and is.binary for the variables).
To silence this warning:
    Call rpart.plot with roundint=FALSE,
    or rebuild the rpart model with model=TRUE.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This decision tree does not bother predicting the league index responses of 2, 7, or 8. This could be because they are rarer classes. This is not the end of the world though, because ranks, 1, 3, 4, 5, and 6 are still being predicted with an accuracy of something higher than 35% (because the entries of rank 2, 7 and 8 are automatically falsely predicted). This result might be prompting me to use a different success metric than accuracy. It is possible that log loss would protect from this mistake to some degree. I will try an upsampling technique instead to artificially increase the size of the un-predicted classes. I will attempt this with decision trees now, and then consider doing this for the remaining models as well.</p>
<p>Otherwise, this best performing decision tree has a tree_depth of 4 and a min_n of 36. It uses only two predictors: ActionLatency and APM. These two predictors were both highly correlated to LeagueIndex so this is fine, though likely there is more than can be predicted. Most importantly though, it tells us that APM and ActionLatency are among, if not, the most important metrics for measuring your performance as a player (outside of game knowledge and strategy). If you are struggling or just trying to improve your rank, then you should monitor your APM and ActionLatency and work on improving both of them.</p>
</section>
<section id="decision-tree-with-upsampling" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree-with-upsampling">Decision Tree with Upsampling</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>dtSpec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">tree_depth=</span><span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>dtRec <span class="ot">&lt;-</span>  <span class="fu">recipe</span>(LeagueIndex <span class="sc">~</span> ., <span class="at">data =</span> train) <span class="sc">%&gt;%</span> </span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(GameID) <span class="sc">%&gt;%</span> </span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Age) <span class="sc">%&gt;%</span> </span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(HoursPerWeek) <span class="sc">%&gt;%</span> </span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(TotalHours) <span class="sc">%&gt;%</span> </span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_smote</span>(LeagueIndex)</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-13"><a href="#cb115-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-14"><a href="#cb115-14" aria-hidden="true" tabindex="-1"></a>dtWf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb115-15"><a href="#cb115-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(dtSpec) <span class="sc">%&gt;%</span> </span>
<span id="cb115-16"><a href="#cb115-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(dtRec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="upsampled-decision-tree-tune" class="level4">
<h4 class="anchored" data-anchor-id="upsampled-decision-tree-tune">Upsampled Decision Tree Tune</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">makeCluster</span>(n_cores <span class="sc">-</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"PSOCK"</span>)</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">tic</span>()</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>dtTuneResults <span class="ot">&lt;-</span> dtWf <span class="sc">%&gt;%</span></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_bayes</span>(</span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> trainFolds,</span>
<span id="cb116-10"><a href="#cb116-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(accuracy),</span>
<span id="cb116-11"><a href="#cb116-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">initial =</span> <span class="dv">20</span>,</span>
<span id="cb116-12"><a href="#cb116-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_bayes</span>(<span class="at">parallel_over =</span> <span class="st">"everything"</span>)</span>
<span id="cb116-13"><a href="#cb116-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! No improvement for 10 iterations; returning current results.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>54.41 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unregister</span>()</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>dtTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 9
   tree_depth min_n .metric  .estimator   mean     n std_err .config       .iter
        &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;         &lt;int&gt;
 1         14    14 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 2          1     6 accuracy multiclass 0.0545    10 0.00355 Preprocessor…     0
 3         13    38 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 4          9    25 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 5         11    31 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 6         15     3 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 7         14    16 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
 8          3    29 accuracy multiclass 0.281     10 0.00814 Preprocessor…     0
 9          4    21 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
10          7    11 accuracy multiclass 0.296     10 0.00971 Preprocessor…     0
# ℹ 20 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co">#54.27  sec elapsed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="upsampled-decision-tree-fit" class="level4">
<h4 class="anchored" data-anchor-id="upsampled-decision-tree-fit">Upsampled Decision Tree Fit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>dtBestParams <span class="ot">&lt;-</span> dtTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"accuracy"</span>)</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>dtBestWf <span class="ot">&lt;-</span> dtWf <span class="sc">%&gt;%</span></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(dtBestParams)</span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a>dtBestFit <span class="ot">&lt;-</span> dtBestWf <span class="sc">%&gt;%</span></span>
<span id="cb123-8"><a href="#cb123-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The fit was successful and will be used with test data at the end of the report.</p>
</section>
<section id="plotting-best-decision-tree-with-upsampling" class="level4">
<h4 class="anchored" data-anchor-id="plotting-best-decision-tree-with-upsampling">Plotting Best Decision Tree with Upsampling</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(dtBestFit <span class="sc">%&gt;%</span> <span class="fu">extract_fit_engine</span>() )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Cannot retrieve the data used to build the model (so cannot determine roundint and is.binary for the variables).
To silence this warning:
    Call rpart.plot with roundint=FALSE,
    or rebuild the rpart model with model=TRUE.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: All boxes will be white (the box.palette argument will be ignored) because
the number of classes in the response 8 is greater than length(box.palette) 6.
To silence this warning use box.palette=0 or trace=-1.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The upsampling was successful in convincing the model to predict for all 8 classes. Because LeagueIndex 8 is missing any data for Age, TotalHours, and HourPerWeek, I had to remove them to get the smote to work. Around 10% accuracy was lost either to the synthetic data or to the 3 missing predictors. Thankfully, none of these 3 predictors were terribly predictive nor were they helpful to interpret past surface level stuff. Because these 3 (now missing) predictors were not used in the best decision tree before, then I suspect the accuracy loss was mostly a result of the synthetic data. After an internal debate, I have decided to go forward with the synthetic data inflation with the reasoning that predicting classes 7 and 8 is important when looking for metrics that predict high performing players. If the missing predicted classes had been all in between other classes (like 2…it predicted class 1 and 3, so it isn’t terribly worrying) then that might have been fine, but it was missing the two highest ranks. The LeagueIndex response is ordered, so missing the two highest values is unproductive for this report. Total hours is not a very helpful metric to need to improve too. If you are looking for what skill to improve, the result should not be total hours or hours per week anyway because you are already going to play more, you are just looking for what skill to improve. Being told to play more doesn’t help. The Age predictor had barely any correlation to LeagueIndex and it has zero helpful interpretability. If you want to improve your skills, being told to be younger doesn’t help. Therefore the loss of these predictors is not significant nor is it lamentable.</p>
<p>Looking at this decision tree closer, it uses more metrics than before as well which is noteworthy. ActionLatency and APM still play perhaps the largest roles. Very importantly though, UniqueHotKeys decides the difference between LeagueIndex 7 and 8. And, MinimapAttacks decides the difference between LeagueIndex 6 and 7,8. This is great because the model is now allowing us to interpret the cut-offs between every rank in the game. Again, this is all accounting for ~30% of the actual factors that lead to a player’s rank, but these are still very helpful metrics to look at when climbing the ranks. A decision tree like this also informs you what metric you should look at depending on which rank you are in, and what metrics you already perform at. And if this decision tree determines you should be in a higher rank than you are in, then you are likely missing game knowledge or strategy. And if this tree determines you should be in a lower rank than you are in, then you are likely over-performing with game knowledge or strategy, while under-performing with these more technical skills. So no matter the situation, a decision tree like this can provide valuable information.</p>
</section>
</section>
<section id="random-forest-model" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-model">Random Forest Model</h3>
<section id="random-forest-setup" class="level4">
<h4 class="anchored" data-anchor-id="random-forest-setup">Random Forest Setup</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>rfSpec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">trees =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>rfRec <span class="ot">&lt;-</span>  <span class="fu">recipe</span>(LeagueIndex <span class="sc">~</span> ., <span class="at">data =</span> train) <span class="sc">%&gt;%</span> </span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(GameID) <span class="sc">%&gt;%</span> </span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Age) <span class="sc">%&gt;%</span> </span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(HoursPerWeek) <span class="sc">%&gt;%</span> </span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(TotalHours) <span class="sc">%&gt;%</span> </span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_smote</span>(LeagueIndex)</span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-13"><a href="#cb127-13" aria-hidden="true" tabindex="-1"></a>rfWf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb127-14"><a href="#cb127-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rfSpec) <span class="sc">%&gt;%</span> </span>
<span id="cb127-15"><a href="#cb127-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(rfRec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the Random Forest model, the “trees” and “min_n” hyperparameters are being tuned. All predictors are used to attempt to predict LeagueIndex. GameId is removed because it is not predictive, it is a label. In the specification, the predictor importance is being tracked so that predictor-level analysis is possible. 20 initial hyperparameter combinations are being used and Bayesian Optimization explores the hyperparamter space further to look for even more optimal solutions. Upsampling is used to balance the classes and encourage the model to predict every class.</p>
</section>
<section id="random-forest-tune" class="level4">
<h4 class="anchored" data-anchor-id="random-forest-tune">Random Forest Tune</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">makeCluster</span>(n_cores <span class="sc">-</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"PSOCK"</span>)</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">tic</span>()</span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a>rfTuneResults <span class="ot">&lt;-</span> rfWf <span class="sc">%&gt;%</span></span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_bayes</span>(</span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> trainFolds,</span>
<span id="cb128-10"><a href="#cb128-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(accuracy),</span>
<span id="cb128-11"><a href="#cb128-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">initial =</span> <span class="dv">20</span>,  <span class="co">#make this bigger after it works</span></span>
<span id="cb128-12"><a href="#cb128-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_bayes</span>(<span class="at">parallel_over =</span> <span class="st">"everything"</span>)</span>
<span id="cb128-13"><a href="#cb128-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! No improvement for 10 iterations; returning current results.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>403.91 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unregister</span>()</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>rfTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 9
   trees min_n .metric  .estimator  mean     n std_err .config             .iter
   &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               &lt;int&gt;
 1  1612    37 accuracy multiclass 0.373    10 0.00564 Preprocessor1_Mode…     0
 2  1717    29 accuracy multiclass 0.371    10 0.00595 Preprocessor1_Mode…     0
 3   894    11 accuracy multiclass 0.373    10 0.00757 Preprocessor1_Mode…     0
 4  1953    10 accuracy multiclass 0.370    10 0.00767 Preprocessor1_Mode…     0
 5  1369    24 accuracy multiclass 0.372    10 0.00625 Preprocessor1_Mode…     0
 6  1551    28 accuracy multiclass 0.370    10 0.00639 Preprocessor1_Mode…     0
 7   514     4 accuracy multiclass 0.367    10 0.00741 Preprocessor1_Mode…     0
 8   400    20 accuracy multiclass 0.375    10 0.00763 Preprocessor1_Mode…     0
 9   661     7 accuracy multiclass 0.371    10 0.00830 Preprocessor1_Mode…     0
10  1435    18 accuracy multiclass 0.372    10 0.00582 Preprocessor1_Mode…     0
# ℹ 20 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#340.81 sec elapsed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The random forest models seems to have around ~35% accuracy which is a great improvement. The best one got ~37.2% accuracy. Again, this makes sense because much of the game is decided by strategy and game knowledge and we have no metrics for those factors at all. The highest performing random forest had 243 trees and a min_n of 5.</p>
</section>
<section id="random-forest-fit" class="level4">
<h4 class="anchored" data-anchor-id="random-forest-fit">Random Forest Fit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>rfBestParams <span class="ot">&lt;-</span> rfTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"accuracy"</span>)</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a>rfBestWf <span class="ot">&lt;-</span> rfWf <span class="sc">%&gt;%</span></span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(rfBestParams)</span>
<span id="cb135-6"><a href="#cb135-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-7"><a href="#cb135-7" aria-hidden="true" tabindex="-1"></a>rfBestFit <span class="ot">&lt;-</span> rfBestWf <span class="sc">%&gt;%</span></span>
<span id="cb135-8"><a href="#cb135-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="random-forest-variable-importance" class="level4">
<h4 class="anchored" data-anchor-id="random-forest-variable-importance">Random Forest Variable Importance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>rfBestFit <span class="sc">%&gt;%</span> </span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span></span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>(<span class="at">num_features =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This variable importance graphic tells us that APM and ActionLatency were chosen most often within the trees. This tells us that these two predictors contribute the most to what LeagueIndex a set of metrics is from. In context, this tells us that APM and ActionLatency are likely the most important metrics to monitor while improving your skill.</p>
<p>SelectByHotkey, GapBetweenPACs and NumberOfPACs are following a bit further behind but are clearly still predictive. It is likely, according to the decision tree above, that these metrics are deciding factors further into the tree. The APM and ActionLatency make the most progress and then these three predictors fill in the gaps.</p>
</section>
</section>
<section id="xgboost-model" class="level3">
<h3 class="anchored" data-anchor-id="xgboost-model">XgBoost Model</h3>
<section id="xgboost-setup" class="level4">
<h4 class="anchored" data-anchor-id="xgboost-setup">XgBoost setup</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>xgbSpec <span class="ot">&lt;-</span> <span class="fu">boost_tree</span>(</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">trees =</span> <span class="fu">tune</span>(), </span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">learn_rate =</span> <span class="fu">tune</span>(), </span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tree_depth =</span> <span class="fu">tune</span>(), </span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">loss_reduction =</span> <span class="fu">tune</span>(), </span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_size =</span> <span class="fu">tune</span>()</span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"xgboost"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb137-9"><a href="#cb137-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb137-10"><a href="#cb137-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-11"><a href="#cb137-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-12"><a href="#cb137-12" aria-hidden="true" tabindex="-1"></a>xgbRec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(LeagueIndex <span class="sc">~</span> ., <span class="at">data =</span> train) <span class="sc">%&gt;%</span> </span>
<span id="cb137-13"><a href="#cb137-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(GameID) <span class="sc">%&gt;%</span></span>
<span id="cb137-14"><a href="#cb137-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Age) <span class="sc">%&gt;%</span> </span>
<span id="cb137-15"><a href="#cb137-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(HoursPerWeek) <span class="sc">%&gt;%</span> </span>
<span id="cb137-16"><a href="#cb137-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(TotalHours) <span class="sc">%&gt;%</span> </span>
<span id="cb137-17"><a href="#cb137-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_smote</span>(LeagueIndex)</span>
<span id="cb137-18"><a href="#cb137-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-19"><a href="#cb137-19" aria-hidden="true" tabindex="-1"></a>xgbWf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb137-20"><a href="#cb137-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(xgbSpec) <span class="sc">%&gt;%</span></span>
<span id="cb137-21"><a href="#cb137-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(xgbRec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the XgBoost model, the “trees”, “learn_rate”, “loss_reduction”, and “sample_size” hyperparameters are being tuned. All predictors are used to attempt to predict LeagueIndex. GameId is removed because it is not predictive, it is a label. 20 initial hyperparameter combinations are being used and Bayesian Optimization explores the hyperparamter space further to look for even more optimal solutions. Upsampling is used to balance the classes to encourage the model to predict every class.</p>
</section>
<section id="xgboost-tune" class="level4">
<h4 class="anchored" data-anchor-id="xgboost-tune">XgBoost Tune</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">makeCluster</span>(n_cores <span class="sc">-</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"PSOCK"</span>)</span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">tic</span>()</span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a>xgbTuneResults <span class="ot">&lt;-</span> xgbWf <span class="sc">%&gt;%</span></span>
<span id="cb138-8"><a href="#cb138-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_bayes</span>(</span>
<span id="cb138-9"><a href="#cb138-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> trainFolds,</span>
<span id="cb138-10"><a href="#cb138-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(accuracy),</span>
<span id="cb138-11"><a href="#cb138-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">initial =</span> <span class="dv">20</span>,  <span class="co">#make this bigger after it works</span></span>
<span id="cb138-12"><a href="#cb138-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_bayes</span>(<span class="at">parallel_over =</span> <span class="st">"everything"</span>)</span>
<span id="cb138-13"><a href="#cb138-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! No improvement for 10 iterations; returning current results.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>tictoc<span class="sc">::</span><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2834.19 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>doParallel<span class="sc">::</span><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unregister</span>()</span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a>xgbTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 12
   trees tree_depth learn_rate loss_reduction sample_size .metric  .estimator
   &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;     
 1   650          1    0.0241    0.0000165          0.594 accuracy multiclass
 2  1475          2    0.00384   0.0642             0.183 accuracy multiclass
 3   365          3    0.00230   0.0000000793       0.493 accuracy multiclass
 4   182          3    0.224     0.413              0.766 accuracy multiclass
 5  1265          4    0.00267   0.000000634        0.628 accuracy multiclass
 6  1640          5    0.0122    0.0000000152       0.297 accuracy multiclass
 7  1052          6    0.00768   0.000731           0.392 accuracy multiclass
 8   887          6    0.238     1.34               0.122 accuracy multiclass
 9  1162          7    0.0172    0.00610            0.830 accuracy multiclass
10  1348          8    0.0623   29.5                0.700 accuracy multiclass
# ℹ 20 more rows
# ℹ 5 more variables: mean &lt;dbl&gt;, n &lt;int&gt;, std_err &lt;dbl&gt;, .config &lt;chr&gt;,
#   .iter &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2462.24 sec elapsed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The best xgboost model had an accuracy of ~36.5% which is about a percent less than the random forest model. It is possible this accuracy difference is negligible, but at the very least it is reinforcing that this dataset is not telling the full story by itself, which again, makes sense. The tree had a tree depth of 5, 566 trees, a learn rate of 0.015233323, a loss reduction of 3.644356e-03 and a sample size of 0.6583793.</p>
</section>
<section id="xgboost-fit" class="level4">
<h4 class="anchored" data-anchor-id="xgboost-fit">Xgboost Fit</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>xgbBestParams <span class="ot">&lt;-</span> xgbTuneResults <span class="sc">%&gt;%</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"accuracy"</span>)</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>xgbBestWf <span class="ot">&lt;-</span> xgbWf <span class="sc">%&gt;%</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(xgbBestParams)</span>
<span id="cb145-6"><a href="#cb145-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-7"><a href="#cb145-7" aria-hidden="true" tabindex="-1"></a>xgbBestFit <span class="ot">&lt;-</span> xgbBestWf <span class="sc">%&gt;%</span></span>
<span id="cb145-8"><a href="#cb145-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="xgboost-variable-importance" class="level4">
<h4 class="anchored" data-anchor-id="xgboost-variable-importance">Xgboost Variable Importance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a>xgbModel <span class="ot">&lt;-</span> <span class="fu">extract_fit_parsnip</span>(xgbBestFit)<span class="sc">$</span>fit</span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">xgb.importance</span>(<span class="at">model =</span> xgbModel)</span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-6"><a href="#cb146-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(importance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Feature       Gain      Cover  Frequency
                  &lt;char&gt;      &lt;num&gt;      &lt;num&gt;      &lt;num&gt;
 1:                  APM 0.18434366 0.11034919 0.07674965
 2:        ActionLatency 0.18223804 0.12140904 0.07737802
 3:      SelectByHotkeys 0.06680101 0.07598340 0.07482980
 4:       GapBetweenPACs 0.06635812 0.08859228 0.08863186
 5:      AssignToHotkeys 0.06631175 0.07711035 0.08058934
 6:       MinimapAttacks 0.06062101 0.06487066 0.07178899
 7:   MinimapRightClicks 0.05308969 0.06809408 0.08144191
 8:          WorkersMade 0.05298846 0.06461674 0.08092089
 9:        UniqueHotkeys 0.05230757 0.05374466 0.05306418
10:         NumberOfPACs 0.04524707 0.06213403 0.06508216
11:         ActionsInPAC 0.04163967 0.05238077 0.06931972
12:     TotalMapExplored 0.03998996 0.04860894 0.06129299
13: ComplexAbilitiesUsed 0.03550456 0.03809906 0.04835297
14:      UniqueUnitsMade 0.03360674 0.04702240 0.04458275
15:     ComplexUnitsMade 0.01895270 0.02698441 0.02597476</code></pre>
</div>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xgb.plot.importance</span>(importance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProj_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>So again, it is reinforced that APM and ActionLatency are the most important predictors. Here, the variable importance is done differently, but I suspect the predictors serve the exact same purpose as they did in the random forest and the decision tree: that is that the APM and ActionLatency do a lot of heavy lifting at the beginning, and then stuff like MinimapAttacks, GapBetweenPACs, and SelectByHotkeys fill in the details. So the most gain is from APM and ActionLatency, but once those are settled, it is the other predictors that make the rest of the difference.</p>
<p>Notably as well, both here and before, the ComplexUnitsMade predictor performed the worst, with the ComplexAbilitiesUsed being better but still second worst. So it does not matter if you are using the complex units or using their abilities. You can succeed without using those units or at least using less of them.</p>
</section>
</section>
<section id="testing-predictive-ability" class="level3">
<h3 class="anchored" data-anchor-id="testing-predictive-ability">Testing Predictive Ability</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a>knnTestResults <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LeagueIndex) <span class="sc">%&gt;%</span> </span>
<span id="cb149-3"><a href="#cb149-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(knnBestFit, test))</span>
<span id="cb149-4"><a href="#cb149-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-5"><a href="#cb149-5" aria-hidden="true" tabindex="-1"></a>knnTestAccuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(knnTestResults<span class="sc">$</span>LeagueIndex <span class="sc">==</span> knnTestResults<span class="sc">$</span>.pred_class)</span>
<span id="cb149-6"><a href="#cb149-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-7"><a href="#cb149-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-8"><a href="#cb149-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-9"><a href="#cb149-9" aria-hidden="true" tabindex="-1"></a>dtTestResults <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb149-10"><a href="#cb149-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LeagueIndex) <span class="sc">%&gt;%</span> </span>
<span id="cb149-11"><a href="#cb149-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(dtBestFit, test))</span>
<span id="cb149-12"><a href="#cb149-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-13"><a href="#cb149-13" aria-hidden="true" tabindex="-1"></a>dtTestAccuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(dtTestResults<span class="sc">$</span>LeagueIndex <span class="sc">==</span> dtTestResults<span class="sc">$</span>.pred_class)</span>
<span id="cb149-14"><a href="#cb149-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-15"><a href="#cb149-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-16"><a href="#cb149-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-17"><a href="#cb149-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-18"><a href="#cb149-18" aria-hidden="true" tabindex="-1"></a>rfTestResults <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb149-19"><a href="#cb149-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LeagueIndex) <span class="sc">%&gt;%</span> </span>
<span id="cb149-20"><a href="#cb149-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(rfBestFit, test))</span>
<span id="cb149-21"><a href="#cb149-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-22"><a href="#cb149-22" aria-hidden="true" tabindex="-1"></a>rfTestAccuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(rfTestResults<span class="sc">$</span>LeagueIndex <span class="sc">==</span> rfTestResults<span class="sc">$</span>.pred_class)</span>
<span id="cb149-23"><a href="#cb149-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-24"><a href="#cb149-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-25"><a href="#cb149-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-26"><a href="#cb149-26" aria-hidden="true" tabindex="-1"></a>xgbTestResults <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb149-27"><a href="#cb149-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LeagueIndex) <span class="sc">%&gt;%</span> </span>
<span id="cb149-28"><a href="#cb149-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(xgbBestFit, test))</span>
<span id="cb149-29"><a href="#cb149-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-30"><a href="#cb149-30" aria-hidden="true" tabindex="-1"></a>xgbTestAccuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(xgbTestResults<span class="sc">$</span>LeagueIndex <span class="sc">==</span> xgbTestResults<span class="sc">$</span>.pred_class)</span>
<span id="cb149-31"><a href="#cb149-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-32"><a href="#cb149-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-33"><a href="#cb149-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-34"><a href="#cb149-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-35"><a href="#cb149-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-36"><a href="#cb149-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-37"><a href="#cb149-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-38"><a href="#cb149-38" aria-hidden="true" tabindex="-1"></a>knnTestAccuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3544118</code></pre>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>dtTestAccuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3176471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>rfTestAccuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3529412</code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>xgbTestAccuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3558824</code></pre>
</div>
</div>
<p>This section has tested the models’ performance on completely new data. This test data is entirely unseen by me or the model, so the results are truly untainted. The worst accuracy was ~31.8% with the decision tree and best accuracy was ~35.6% with the XGBoost model. Both the random forest and the KNN model were just below the XGBoost model with ~35.3% and ~35.4% accuracy respectively. These results are good because they are in line with our estimates using our cross validation techniques. This supposes that our models are not overfit meaning that they are predicting real patterns and not just noise. The reapperance of the ~35% accuracy as well as all the models having a similar accuracy suggest that, again, around 35% of a player’s rank can be attributed to these technical skills within the dataset. Outside of this ~35% lies game strategy, game knowledge and luck, likely among other things.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Because the intention of this report was not to predict the LeagueIndex of new player data, it can be said to be a success. The models created would not perform well to predict the LeagueIndex of new data, and nor should it. If it did, it would suggest that game knowledge and strategy do not play a large part of what rank a player is in, which would be alarming. With more intensive tuning, the accuracy would likely go up a bit more, but I am unsure the limit. Whatever that limit is, it can be considered the amount that the predictors contribute to to a player’s rank in Starcraft 2. That limit seems to be around ~35% based on the models we tuned and fit. The remaining ~65% that is unpredicted by our models is likely attributable to game knowledge, strategy, hours played, and luck. What this report confirms, is that around 35% of the reason for a player’s rank are the metrics used as predictors for these models. All of which can be recorded automatically while playing the game. 35% is not a small amount when looking to improve one’s skills, and these metrics are all measurable and measurably improvable.</p>
<p>So, if you are playing Starcraft 2, and you intend to climb the ranks, you should track these metrics paying special attention to APM and ActionLatency. You should see what you can do to improve these skills, which mostly includes thinking faster and acting faster. Most importantly though, you should match your values of these metrics to those in the decision tree and then, if you get the rank you are in, you should look at what would put you in the next rank up. For the lower ranks, it is likely the case that you just need to improve APM and ActionLatency, but going into the 6,7,8 ranks, you may need to switch your focus to MinimapAttacks, GapBetweenPACs, SelectByHotkeys, or AssignToHotkeys. And if you improve these values, but do not improve rank, then you need to focus on game knowledge and game strategy. In that case you should learn some playstyles and playstyle counters.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>